<?php

namespace AddressBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function loadAllAboutContact($id, $userId)
    {
        $dql = "SELECT c,a,e,p,g,u FROM AddressBookBundle:Contact c 
                LEFT JOIN c.addresses a
                LEFT JOIN c.emails e
                LEFT JOIN c.phones p
                LEFT JOIN c.groups g
                LEFT JOIN c.user u
                WHERE c.id=:id
                AND u.id=:userId";

        return $this->getEntityManager()->createQuery($dql)
            ->setParameter('id', $id)
            ->setParameter('userId', $userId)
            ->getOneOrNullResult();
    }

    public function findContactsLike($search, $userID)
    {
        $dql = "SELECT c FROM AddressBookBundle:Contact c 
                WHERE CONCAT(c.name,' ',c.surname) LIKE :search 
                AND c.user =:userID
                ORDER BY c.surname ASC";

        return $this->getEntityManager()->createQuery($dql)
            ->setParameter('search', '%'.$search.'%')
            ->setParameter('userID', $userID)
            ->getResult();
    }

    public function loadAllWithGroup($groupId)
    {
        $dql = "SELECT c, g FROM AddressBookBundle:Contact c 
                LEFT JOIN c.groups g
                WHERE g.id =:id";

        return $this->getEntityManager()->createQuery($dql)
            ->setParameter('id', $groupId)->getResult();
    }
}
